permalink: /:year/:title/
_options:
  layout:
    hidden: true
  language:
    hidden: true
  rooms-title-2:
    hidden: true
  news-title:
    hidden: true
  contact-name-placeholder:
    hidden: true
  contact-email-placeholder:
    hidden: true
  contact-message-placeholder:
    hidden: true
  contact-send-button:
    hidden: true
  address-title:
    hidden: true
  address:
    hidden: true
  city:
    hidden: true
defaults:
  - type: 'index.html'
    values:
      _hide_title: true
